version: 0.0
os: linux

hooks:
  AfterInstall:
    - location: ./codedeploy/install.sh
      timeout: 900
      runas: ubuntu
  ApplicationStart:
    - location: ./codedeploy/start.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: ./codedeploy/end.sh
      timeout: 300
      runas: ubuntu
