version: 0.0
os: linux

hooks:
  AfterInstall:
    - location: codedeploy/install.sh
      timeout: 900
      runas: root
  ApplicationStart:
    - location: codedeploy/start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: codedeploy/end.sh
      timeout: 300
      runas: root
