version: 0.0
os: linux
files:
 - source: /
   destination: /home/webapp

hooks:
  AfterInstall:
    - location: ./codedeploy/start.sh
    - location: ./codedeploy/end.sh
  ApplicationStart:
    - location: ./codedeploy/startcloudwatch.sh
